spring.application.name=self_introduction

# 1) ?? ?? ??
logging.level.root=INFO

# 2) ?? ?? ??
logging.file.name=logs/app.log

# 3) ?? ?? ??
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.level.org.example.self_introduction.repository=DEBUG
logging.level.org.example.self_introduction.aspect=DEBUG